### PR TITLE
Update dotnet version and fix linux issues

### PR DESCRIPTION
**Pull request by veyxov**

### CODE REVIEW

**Comment by Vjake** [comment]
@veyxov I refactored all code because it was sort of old and unstable (https://github.com/Vjake/ConsoleRender/pull/2). Can you look at it?

**Comment by veyxov** [comment]
Great job!

**Comment by veyxov** [comment]
All the issues that this PR fixed are already fixed in your new version.

**Comment by Vjake** [comment]
Thank you

**Pull request closed without merging**
